### ISSUE TITLE
Add detailed recommendations about Github organizations & distributed workflow

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/overview#16]
We should make stronger recommendations about the use of Github organizations as a structure for both individual events and the longer-term project.  In particular, we should outline forking/merging recommendations for a spoke-hub structure.

**Comment by atesgoral** [comment]
I would also recommend the use of rebase over merge to keep commit histories clean.

**Comment by titaniumbones** [comment]
(are you perhaps referring to my accidental-merging disaster, polluting all the commit histories for all eternity)?

**Comment by dcwalk** [comment]
@atesgoral can you clarify the cases when you would prefer rebase?

I think some of this could be captured in: #10 contributor guidelines

**Comment by atesgoral** [comment]
@dcwalk If everyone is strictly following a workflow through PRs (i.e. not committing directly to master), the only merge commits there would ever need to be are PR merge commits, which can be cleanly ported over if needed to other branches.

For synchronizing development streams with branches that are ahead, a rebase (strictly without squashing!) paints a better mental model than a merge because it is just a replay of commits by someone else on top of commits by others, rather than unintuitive file diffs created by a merge between two arbitrary snapshots of code. Everyone's intentions and actions are preserved in the commit history (this is assuming there's also a culture of topical commits with clear commit comments).

I'm on the rebase camp, especially when it comes to maintenance of open source projects. A "rebase vs merge" search on Google yields a plethora of results talking about pros and cons of each approach, so I can't really point you to one particular resource to argue for rebasing. It's just that my personal experience from using both approaches over many years has put me on the rebase camp.

**Comment by dcwalk** [comment]
@atesgoral we had discussed and recommended working exclusively through PRs (as stubbed out in #10) and branches or local repos (tho this is something that can/should be discussed)

I think it would be good to provide some guidance to people on rebasing as we can't expect everyone will have lots of experience, however given that we are aiming to use PRs I'm not sure how or how critical that is to include?

**Comment by titaniumbones** [comment]
@atesgoral I think rebasing is just a little bit harder to understand for the less-technical (like myself).  OTOH there is some low-hanging fruit that could maybe go in a `contributing` document: 

Contributors: before submitting a PR please :squash" your commits by doing an interactive rebase (as described, e.g., [here](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request#squash-your-changes)).  Also there are some other circumstances where we would prefer you to rebase rather than merge, which @atesgoral will explain in just 2 sentences when he edits this."

**Comment by dcwalk** [comment]
I think this can be addressed as part of #49

**Comment by dcwalk** [comment]
I am closing this as stale, we've (many times) revamped event workflow. Our next iteration will handle this stuff differently as well!
