### ISSUE TITLE
Decide on some default labels for probot configurer plugin

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/overview#172]
I've added the ["probot: configurer" plugin](https://github.com/apps/configurer) to a few repos -- this basically allows repo config to be set from a yaml file in code, ie. by anyone who can submit a PR :)

https://github.com/edgi-govdata-archiving/edgi-hubot/pull/27

I've been using it for repo descriptions/urls, but we can also use it for labels.

The one label I would 100% use across all our repos is the "first-timer" label. Any other suggestions?

Other questions:
1. `first-timer` vs `first-timer-only`?
    - Specifically, do we want separate labels for saying both "easiness" and saying "mature contributors, please don't touch this"?
3. Gratipay interestingly used stars for priority, but we could repurpose them for difficulty? ie:
    - `★☆☆`
    - `★★☆`
    - `★★★`

cc: @dcwalk :)

**Comment by dcwalk** [comment]
1. I'd suggest `first-timer` mostly because it is shorter and we've already implemented across a few repos.
I know a couple projects use a range of labels so I don't see a clear more popular one? (e.g., http://up-for-grabs.net/ or http://www.firsttimersonly.com/)

2. Just keen on stars as a difficulty indicator.

Just to zoom out a bit: what motivated the move to probot?

**Comment by patcon** [comment]
I'll open a new ticket explicitly for probot:settings plugin discussion, because you're totally right that it didn't get convo :)

I see that this repo now has priority-star labels, so that seems dealt with

Clear success criteria in #179, so that's better than this one.

In light of above, closing! :heart:
