### ISSUE TITLE
The "idea" label and stalebot exemption

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/overview#231]
From a conversation at https://github.com/edgi-govdata-archiving/overview/pull/230#discussion_r271905317 with @lightandluck, wanted to be more explicit about how we're using the "idea" label.

Personally, I had taken "idea" at face value, to label issues as ideas we're floating.

Web Monitoring is exempting "idea"-labeled issues from stalebot. I had thought this was to keep ideas around (a perfectly valid thing to do, though it would not be my preference).

@lightandluck explained further:
> In WM, `idea` is used **only** to exempt issues from stalebot. It isn't applied it to anything else. WM was trying to find a succinct term that signified an issue was far off and not have stalebot ping us anymore.

It sounds like it would be a good idea to have a label in our standard set that is stalebot-exempt, but I'd propose something more explicit like `stalebot-exempt` or `pinned`. What is the consensus on this? Would be great to incorporate this into https://github.com/edgi-govdata-archiving/overview/pull/230

**Comment by lightandluck** [comment]
I think going with the default `pinned` would reduce confusion and we certainly need & want an exemption label.

If we do, I feel we should just drop `idea` because that was its only function. I don't think such an amorphous term adds much and is almost as redundant as having a label called `issue`. 

We do have the problem of going back and fixing issues in WM if we make this change, but I'm willing to clean up and re-label things if that's what we decide.

**Comment by Frijol** [comment]
Any input from others in WM (@Mr0grog in particular)?

**Comment by patcon** [comment]
what about just `never-stale` or `not-stale`, (or even `forever-fresh` or `always-fresh`)? Then it's more clearly tied to it's purpose -- no need to stumble on docs that `idea`/`pinned` means for stalebot to ignore it :)

**Comment by patcon** [comment]
Also, "pinned" refers to an uncommon state of native github issues as well:

![Screen Shot 2019-04-20 at 7 14 39 PM](https://user-images.githubusercontent.com/305339/56463365-a83d0800-63a0-11e9-997e-d5e132589636.png)

**Comment by Mr0grog** [comment]
> Web Monitoring is exempting "idea"-labeled issues from stalebot. I had thought this was to keep ideas around (a perfectly valid thing to do, though it would not be my preference).
>
> @lightandluck explained further:
>
>> In WM, idea is used only to exempt issues from stalebot. It isn't applied it to anything else. WM was trying to find a succinct term that signified an issue was far off and not have stalebot ping us anymore.

Oh, no, I use both `idea` and `pinned`, and use them as you had expected, @Frijol. e.g:
- Pinned: https://github.com/edgi-govdata-archiving/web-monitoring-db/issues/379
- Idea: https://github.com/edgi-govdata-archiving/web-monitoring-db/issues/199

But if we really wanted just one, I think `pinned` is clear. Also, IIRC, it’s @danielballan who had stronger opinions here.

*(Update: changed the example link for “pinned” to an issue that is less fuzzy about which label is more fitting.)*

**Comment by Mr0grog** [comment]
> Also, "pinned" refers to an uncommon state of native github issues as well

Yeah, that is definitely an unfortunate collision. If we want the label to just be explicitly for this purpose, I think your `never-stale` suggestion is best. I think the original idea with `idea` was that we wanted to avoid having a label that was purely a signal to some technical tool we're using (stalebot) and not meaningful for humans. That may have been a bad fundamental approach, though.

I definitely agree that in many (maybe most?) situations, the choice between `pinned` and `idea` is a bit fuzzy, especially when we also have `question` (mainly to mark the transition from speculative idea to one we have clearer intent & design for). Making the label only be about stalebot would certainly remove that fuzziness, since it wouldn’t be *descriptive* in any way.

**Comment by Mr0grog** [comment]
(Also, sorry, I have been *buried* trying to finish a client project this past week, and I haven’t been keeping up very well with EDGI issues.)

**Comment by lightandluck** [comment]
Sorry, that I misunderstood. That fuzziness probably contributed for my confusion.

+1 with going with `never-stale`. Thanks @patcon for pointing out that github has a `pinned` state, too.

**Comment by danielballan** [comment]
:+1: for `never-stale`

**Comment by Frijol** [comment]
Sounds good. Circling back, I think we decided:

* [x] There should be a standard core label `never-stale` which is exempt from stalebot (action: update list of core labels in template and apply to repos, update stalebot yml file in each repo and in the template)
* [x] There still exists a standard core label `idea` but it is not exempt from stalebot (action: change labels on WM repos to `never-stale` where appropriate, remove `idea` from stalebot's yml file there)

Sound correct? Does that cover everything?

**Comment by Mr0grog** [comment]
Makes sense to me!

**Comment by lightandluck** [comment]
That sounds good 👍

**Comment by Frijol** [comment]
**Help needed**: Here are [all the issues labeled `idea`](https://github.com/issues?q=is%3Aopen+is%3Aissue+label%3Aidea+user%3Aedgi-govdata-archiving). I made sure a `never-stale` label exists on all of those repos. Can someone from WM (probably @Mr0grog) please sort out which issues should be `idea` labeled vs. `never-stale`?

(I updated the stalebot yml for all repos to exempt `never-stale` but have left `idea` exempted in the repos where it was exempt pending sorting out which is what)

**Comment by Mr0grog** [comment]
I took a pass at re-tagging where it seemed appropriate across all the web-monitoring projects.

**Comment by lightandluck** [comment]
I created PRs to remove `idea` from exempt labels in the WM repos. I _think_ it's ok to do that now? Just need an approval for one and I'll merge them all in.

**Comment by Frijol** [comment]
Thanks all!
