### ISSUE TITLE
Add a bot that explains our "it's ok to merge after X time without review" policy

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/overview#238]
EDGI (or at least web monitoring) typically has an "ok to merge" policy for any straightforward PR that hasn't gotten reviews after 3 days. It would be nice to have a bot call this out on PRs that sit for 3 days without any interaction. (Otherwise the contributor might not be aware of this policy)

**Comment by Mr0grog** [comment]
For web monitoring, at least, I don’t think we really have many contributors with commit rights, so it feels like it’s easy enough to teach people this when giving them commit rights.

But also: I have stopped following this policy much of the time for the past several months (though I did talk that through with other contributors). Because we have so few active contributors, the policy mostly just adds delay. I still adhere to it if I don’t feel exceedingly confident (it forces me to “sleep on it” and review again with a clearer head) or if I’m working in an area where other contributors are really active (parts of web-monitoring-ui and wayback).
