### ISSUE TITLE
Implement onboarding process for Archivers App (Event Preservation) development

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/overview#64]
Coming out of our [Feb 14 Standup](https://hackmd.io/EYDgpg7ArAnDIFoAMUDGBmBAWd7gIEMCBGAEwVJHVQCYIQAzSiMIA===#), @danielballan is looking to open up development for the Archivers app, especially as we have more people interested in contributing.

TODOs to mark this complete:
- [x] kickoff meeting (see notes below)
- [x] security sign-off (related to #50) -- call with a plan to go ahead:
- [x] contributer guidelines added
- [x] public github for archivers ROADMAP, **target date of Friday March 17:**
  - [x] 1. code cleanup/linting complete
  - [x] ~2. integration of security middleware into dev process per @zsck’s recommendation~ (turns out these were for Express framework so followed [Meteor's security checklist](https://guide.meteor.com/security.html)
  - [x] 3. Add middleware recommendations to org-wide project guidelines
  - [x] 4. identify areas of codebase that are of concern and open issues (e.g. memory usage, imports api)
  - [x] 5. address https redirect and ensure CORS handling okay
  - [x] 6. throw a license on the code

**Comment by dcwalk** [comment]
We have a slick public issues repository :)) https://github.com/edgi-govdata-archiving/archivers.space

**Comment by dcwalk** [comment]
@danielballan or @b5 --
Could you provide a brief update on the outcomes from the meeting on Saturday?
Or point me at any notes/documentation?

**Comment by kmcculloch** [comment]
@dcwalk No formal notes, although I believe @b5 recorded our conversation. @khdelphine and @titaniumbones also attended, and a couple of other folks I don't know yet.

Here's how I'd summarize what I heard:

- @b5 is working on the long-term vision for our tools, including standardizing metadata across efforts and addressing some of the issues in https://github.com/edgi-govdata-archiving/dataset-registries/issues/1. The general vision is that harvesting and monitoring work should ultimately be automated, and that the real challenge is to engage volunteers with domain-specific knowledge of the data in order to help with describing data, grooming metadata, and so forth.
- It's an open question as to whether current tools like archivers.space morph into a richer application for achieving that goal, or whether they will be replaced by something else. The short-term vision for archivers.space is that it will continue to support the workflow as it's currently defined and that we will focus on changes that help to refine the user interface and help with maintenance and clean-up of the data that's already in the app.
- We will use the issue queue at https://github.com/edgi-govdata-archiving/archivers.space/issues as a backlog for archivers.space. I've just developed a set of tags to help categorize issues and a project board at https://github.com/edgi-govdata-archiving/archivers.space/projects/1 to help us prioritize.

I've offered to act as something like a project manager for archivers.space. I can maintain the issue queue, monitor priorities and track work, and I should be able to produce pull requests, too, as I become better acquainted with the js frameworks we're using. But I still need stakeholder help with the following:

1. Making sure that every proposed/desired app change is in the issue queue.
2. Participating in conversations in the issue queue. Even a simple "I want this too" comment will help me identify priorities. Also, some of the issues are old and may already have been addressed, so I need to know if old ones are still important.
3. Grooming the backlog by identifying the most important issues so we can address them first.

**Comment by dcwalk** [comment]
@kmcculloch Wonderful, thanks for the detailed notes, and good to know you are in a project lead role for the app.

What is the status/thoughts around security review and opening the code?

**Comment by kmcculloch** [comment]
@dcwalk Good question. We'll need to consult @b5 or get another volunteer who is qualified to do a security review of meteor code. Also, we still need to have a conversation about review and approval of pull requests and deployment--I don't know anything about the environment where the code is running or about backups, data recovery and so forth. The conversation on Saturday wasn't technical.

**Comment by dcwalk** [comment]
Okay, shall we take up some of these questions via issues in the archivers.space repo? 
We have standard contrib guidelines that could be extended to cover specifics for deploy. 

I have worked on projects where we specify some elements of backups, infrastructure etc... in a public meta repo like [overview](https://github.com/edgi-govdata-archiving/overview) which works okay-ish.  Or we could add that info to the archivers.space repo. 

My main concern besides what should be publicly documented will be consistency across all our projects and also the right balance of public and private

**Comment by kmcculloch** [comment]
Here's an issue for the security review: https://github.com/edgi-govdata-archiving/archivers.space/issues/47

**Comment by kmcculloch** [comment]
The security review is complete and the archivers.space code is now public.

**Comment by dcwalk** [comment]
Great, I'm remiss in adding the adding the middleware suggestions to the Project Guidelines... opening a PR #105. Gonna close this as onboarded 🎉 y'all rock :)
